"""
This type stub file was generated by pyright.
"""

"""Contains sets of English words from obtained from https://svnweb.freebsd.org/csrg/share/dict/.

There are four sets in this module:

english_words_set: A set of English words containing both upper- and
    lower-case letters; with punctuation.
english_words_lower_set: A set of English words containing lower-case
    letters; with punctuation.
english_words_alpha_set: A set of English words containing both upper-
    and lower-case letters; with no punctuation.
english_words_lower_alpha_set: A set of English words containing
    lower-case letters; with no punctuation.
"""
english_words_set: set[str] = ...
english_words_lower_set: set[str] = ...
english_words_alpha_set: set[str] = ...
english_words_lower_alpha_set: set[str] = ...
